
app = "dictionary-api-tbrpta"   # nombre de tu app
primary_region = "ams"           # región cercana a tus usuarios

[build]

[http_service]
  internal_port = 8080          # la app escucha en 0.0.0.0:$PORT
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "256mb"              # Free Tier
  cpu_kind = "shared"
  cpus = 1
